- name: User
  hosts: all
  sudo: true
  tasks:
  - name: Clone repository
    git: repo=https://github.com/pdostal/server-scripts.git dest=/root/scripts

  - name: Ensure .profile exists
    file: path=/root/.profile state=touch mode=700
  - name: Include .bashrc
    lineinfile: dest=/root/.profile create=yes regexp=~/.bashrc line='source ~/.bashrc'

  - name: Paste master config
    template: >
      src=templates/bashrc
      dest=/root/.bashrc

