- name: User
  hosts: all
  sudo: true
  tasks:
  - name: Clone repository
    git: repo=https://github.com/pdostal/server-scripts.git dest=~/scripts

  - name: Ensure .profile exists
    file: path=~/.profile state=touch mode=700
  - name: Include .bashrc in .profile
    lineinfile: dest=~/.profile create=yes regexp=~/.bashrc line='source ~/.bashrc'

  - name: Paste .bashrc config
    template: >
      src=templates/bashrc
      dest=~/.bashrc

